<?
/*
	PolyPager - a lean, mean web publishing system
    Copyright (C) 2006 Nicolas Hšning
	polypager.nicolashoening.de
	
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA' .
*/

header("Content-type: text/javascript; charset=iso-8859-1");

// FILE SEPARATOR
if ( !defined('FILE_SEPARATOR') ) {
    define('FILE_SEPARATOR', ( substr(PHP_OS, 0, 3) == 'WIN' ) ? "\\" : '/');
}
include_once('..'.FILE_SEPARATOR.'lib'.FILE_SEPARATOR.'PolyPagerLib_Utils.php');
$sys_info = getSysInfo();

?>
/*----------------------------------------------------------------
  This JavaScript was generated by PolyPager 
  see http://polypager.nicolashoening.de
  ----------------------------------------------------------------*/
  
// id browsers
var name = navigator.userAgent.toLowerCase()
var opera = (name.indexOf("opera")> -1) //this is just Opera
var iex=(document.all);	//this can also be Opera!
var nav=(document.layers);
var old=(navigator.appName=="Netscape" && !document.layers && !document.getElementById);
var n_6=(window.sidebar);

function getElementsByClass(classname){
	var elements = new Array();
	var inc = 0;
	var alltags = document.all? document.all : document.getElementsByTagName("*");
	for (i = 0; i < alltags.length; i++){
		if (alltags[i].className == classname)
			elements[inc++] = alltags[i];
	}
	return elements;
}

function toggleVisibility(theElementID, theLinkID, text_invis, text_vis) {
	el = get(theElementID);
	theLink = get(theLinkID);
	theLinkNester = get(theLinkID+'_nester');
	if (el.style.display == 'none' || el.style.display == '') {
		el.style.display = 'block';
		theLink.innerHTML = text_vis;
		if(theLinkNester) theLinkNester.className = 'clicked';
	} else {
		el.style.display = 'none';
		theLink.innerHTML = text_invis;
		if(theLinkNester) theLinkNester.className = '';
	}
}


function toggle_ability(theClass) {
	var inputs = getElementsByClass(theClass);
	var l = inputs.length;
	for (var i = 0; i < l; i++) {
		var e = inputs[i];
		if (e.disabled == true) {
			e.disabled = false;
		} else {
			e.disabled = true;
		}
	}
	var link = document.getElementById(theClass + "_link");
	<? $path_from_docroot = getPathFromDocRoot(); 
		$pic_url = str_replace("\\", '/', $path_from_docroot).'style/pics/'; ?>
	if (link.style.backgroundImage.match('.*ok.*'))
		link.style.backgroundImage = "url(<? echo($pic_url);?>no.gif)";
	else link.style.backgroundImage = "url(<? echo($pic_url);?>ok.gif)";
}

function toggleMenuVisibility(menu_name) {	
	var menu;	 	//holds the actual submenu to show (menu_name + "_menu")
	var main_li;  	//the main_menu li actually klicked
	var main_a;		//the main_menu a actually klicked
	//hide all submenus - we only show one
	<?
	$pages = getPages();
	foreach($pages as $p) {
		if ($p["in_menue"] == "1") {
			//echo('	menus[menus.length] = get("'.$p["name"].'_menu");'."\n");
			echo('	menu = get("'.$p["name"].'_menu");'."\n");
			echo('	if (("'.$p["name"].'" != menu_name) && menu) menu.style.visibility = "hidden";'."\n");
		}
	}
	?>
	
	//also, turn off all bg-images in the main-menu elements
	<?
	foreach($pages as $p) {
		if ($p["in_menue"] == "1") {
			echo('	main_li = get("'.$p["name"].'_li");'."\n");
			echo('	if (main_li) main_li.className = "not_here";	//'."\n");
		}
	}
	?>
	
	//now, toggle visibility
	menu = get(menu_name+"_menu");
	if (menu.style.visibility == "visible") {
		menu.style.visibility = "hidden";
	} else {
		menu.style.visibility = "visible";
	}
	
	//maintain bg doors of the klicked entry
	main_li = get(menu_name+"_li");
	main_li.className = "here";

}

// get an element - the function is similar to "$()" used in prototype.js
function get(e_name) {
	var the_element;
	if (document.getElementById) {                            // W3C DOM
		the_element = document.getElementById(e_name);
	} else if (document.all) {                                // IE4
		the_element = document.all[e_name];
	} else if (document.layers) {                             // NS4
		the_element = document.layers[e_name];
	}
	return the_element;
}

// appends ", " + source.innerHTML
// to target and makes source invisible
var hidden_links = new Array();
var first_time_over = 0;
var initial_state = ''
function moveContent(target, source) {
	target_element = get(target);
	if (first_time_over == 0){
		first_time_over = 1;
		//just remembering what had been here at loadtime
		initial_state = target_element.value;
	}
	source_link = get(source);
	var sep = "";
	if(target_element.value != "") sep = ","
	target_element.value = target_element.value + sep + source_link.innerHTML;
	source_link.style.visibility = 'hidden';
	source_link.style.position =  'absolute';
	source_link.style.top = getMetric(-10000);
	source_link.style.left = getMetric(-10000);
	hidden_links[hidden_links.length] = source;
}

function getMetric(num) {
	if(n_6) { return parseInt(num) + 'px';}
	else return parseInt(num);
}

function reset(inputfieldname){
	if (first_time_over != 0){
		infield = get(inputfieldname);
		infield.value = initial_state;
		for(i=0;i<hidden_links.length;i++) {
			hlink = get(hidden_links[i]);
			//make it appear again
			hlink.style.visibility = 'visible';
			hlink.style.position =  'relative';
			hlink.style.top = getMetric(0);
			hlink.style.left = getMetric(0);
		}
	}
}

/* open link in a new window */
function openWindow(adress, title, width, height, top, left, scrollbars) {
	fenster = window.open(adress, title, "width="+width+",height="+height+",left="+left+",top="+top+",scrollbars="+scrollbars);
	fenster.focus();
}

//asks if deleting is really wanted
function checkDelete(){
	agree = confirm("<?echo(__('Are you sure you want to delete this entry?'));?>");
	if (agree) {
   		//document.form1.submit();
		return true;
	}
	else {
   		return false;
	}
} 

function submit_form_by_selection(command) {
	agree = confirm('<?=__('a change this field is important for other fields in this form. I therefore would like to reload this page. OK?')?>');
	if (agree) {
		get('the_real_cmd').value=command;
		document.forms[0].submit();
	}
}

//checks input values of forms
function checkValues(pageName) {
	var results = "";
	var tmp = "";
	//alert("checking " + pageName);
	
	/*if (pageName=="_sys_singlepages") {
		if (isNaN(document.forms[0].menue_index_input.value)) {
			results = results + "The field menue_index contains a non-numeric value!\n\n";
		}
	}*/
	if (pageName=="_sys_sections") {
		if (isNaN(document.forms[0].order_index_input.value)) {
			results = results + "The field order_index contains a non-numeric value!\n\n";
		}
	}
	<? $mpages = getPageNames();
	$mpages[count($mpages)] = '_sys_singlepages';
	$mpages[count($mpages)] = '_sys_multipages';
	$mpages[count($mpages)] = '_sys_comments';
	foreach($mpages as $p) { ?>
		if (pageName=="<?=$p?>") {
			//alert('I AM HERE for page ' + pageName);
			<? $act_entity = getEntity($p);
			$fields = $act_entity["fields"];
			if ($fields != "") {
				foreach($fields as $f) {
					//it seems there is a problem here for hidden fields ???
					if($f["data_type"] == 'int' or $f["validation"] == 'number') { ?>
					//	if (isNaN(document.forms[0]._formfield_<?=$f["name"]?>_input.value)) {
					//		results = results + "The field \"" + document.forms[0].<?=$f["name"]?>.name + "\" contains a non-numeric value!\n\n";
					//	}
					<?}
					if($f["data_type"] == 'real') { ?> //this should be implemented as regex! sthg like [[0-9]+\.[0-9]*|[0-9]*\.[0-9]+]
					//	if (isNaN(document.forms[0]._formfield_<?=$f["name"]?>_input.value)) {
					//		results = results + "The field \"" + document.forms[0].<?=$f["name"]?>.name + "\" contains a non-numeric value!\n\n";
					//	}
					<?}
					else if(getValidationRegex($f["validation"]) != '') { ?>
						
						var field = document.forms[0]._formfield_<?=$f["name"]?>_input;
						if (field) {
							tmp = field.value;
							regex = '<?=getValidationRegex($f["validation"])?>';
							msg = '<?=getValidationMsg($f["validation"])?>';
							var erg = tmp.match(<?=getValidationRegex($f["validation"])?>); 
							if (!erg) {
								results = results + "<?=__($f["name"])?>: " + msg + "\n\n";
								results = results + "<?echo(__('In detail: the content'));?> \"" + tmp + "\" <?echo(__('of the field'));?> \"<?=__($f["name"])?>\" <?echo(__('does not match the Regular Expression'));?> \"" + regex + "\"!\n";
								results = results + "\n\n";
							}
						}
					<?}?>
					
				<?}
			}?>
		}
		
	<?}?>

	<?
	$text = __('The following of the data you entered do not meet the given specifications:');
	?>
	if (results != "") {
		results = "<?echo($text);?>\n\n" + results;
		alert(results);
		return false;
	}
	return true;
}
